### ISSUE TITLE
Add timestamp support in reservations

### ISSUE THREAD

**Issue by dhondo01** [RoomReserve/RoomReserve#124]

**Comment by dhondo01** [comment]
Done!

**Comment by dhondo01** [comment]
For this to work on heroku, the database has to be reset. It does not have timestamp module.

**Comment by ryanpoints** [comment]
If we are going to reset the data anyway, then yes. But I can go in and manually add the table if we don't want to reset.

It may be a good idea to reset the database anyway before we fill it with things for the presentation.

**Comment by dhondo01** [comment]
I agree, if we reset the database let's add only good fake data after that.

**Comment by ryanpoints** [comment]
Okay, good. Lets reset today during our meeting.

**Comment by dhondo01** [comment]
Sounds good.

**Comment by ryanpoints** [comment]
This is almost resolved. The timestamp is always "a few seconds ago"
@dhondo01 is currently changing the implementation from moment.js to a column in the database called `timestamp`.

The `timestamp` on the reservation table will be set in the `Reservation.__init__()`

**Comment by dhondo01** [comment]
I'm on it!

**Comment by dhondo01** [comment]
Fixed!
