### ISSUE TITLE
Housekeeping view

### ISSUE THREAD

**Issue by ryanpoints** [RoomReserve/RoomReserve#52]
Add a view for rooms that need to be cleaned.
- When a room is checked out, it becomes "dirty"
- Dirty rooms remain dirty until they are cleaned.
- Dirty rooms can't be checked in without a warning until they are marked clean.
- A new housekeeping view shows:
  - A list of rooms that have been checked out, but not yet cleaned
  - Buttons to mark rooms as clean

**Comment by stekza01** [comment]
Completed.
