### ISSUE TITLE
Remove sortable option on Edit columns on DataTables tables

### ISSUE THREAD

**Issue by ryanpoints** [RoomReserve/RoomReserve#59]
$(document).ready(function() {
  $('#example').dataTable( {
    "aoColumns": [
      null,
      null,
      { "bSortable": false }
    ] } );
} );

**Comment by ryanpoints** [comment]
This'll require some reworking on initializing the Table in myjs.js
Project for another day.

**Comment by dhondo01** [comment]
Yes, that's minor bug but we will fix it soon.

**Comment by dhondo01** [comment]
Sorting the edit button won't change anything anyways, at least from what I have tested.

**Comment by dhondo01** [comment]
I guess we can not assign two assignees haha

**Comment by ryanpoints** [comment]
Yes it is minor but it will look better. I know how to do it but I'll do it
another day.

**Comment by dhondo01** [comment]
Sounds good.

**Comment by dhondo01** [comment]
https://datatables.net/reference/option/columns.orderable

**Comment by dhondo01** [comment]
I fixed it. The commit is [here](https://github.com/RoomReserve/RoomReserve/commit/15ac26812d3d7b1d4dda3f13797bf47e17d8fdd5)
